title: Christian Helle's Blog
email: christian.helle@outlook.com
description: >-
  This blog is dedicated to the art of building software.
  I write about my creations, discoveries, and solutions to problems
  that I encounter while building software.

baseurl: "/"
url: "https://christianhelle.com"
twitter_username: christianhelle
github_username:  christianhelle

markdown: kramdown
highlighter: rouge

theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - { platform: facebook,         user_url: "https://www.facebook.com/christianresmahelle" }
    - { platform: github,           user_url: "https://github.com/christianhelle" }
    - { platform: instagram,        user_url: "https://www.instagram.com/chresmahelle" }
    - { platform: keybase,          user_url: "https://keybase.io/christianhelle" }
    - { platform: linkedin,         user_url: "https://www.linkedin.com/in/christianhelle" }
    - { platform: microdotblog,     user_url: "https://micro.blog/christianhelle" }
    - { platform: pinterest,        user_url: "https://www.pinterest.com/christianhelle/" }
    - { platform: stackoverflow,    user_url: "https://stackoverflow.com/users/575374/christian-resma-helle" }
    - { platform: telegram,         user_url: "https://t.me/christianhelle" }
    - { platform: twitter,          user_url: "https://twitter.com/christianhelle" }
    - { platform: mastodon,         user_url: "https://techhub.social/@christianhelle" }
    - { platform: mastodon,         user_url: "https://mastodon.social/@christianhelle" }

paginate: 1
paginate_path: /page/:num/
defaults:
 - 
   scope:
     path: "page"
   values:
     sitemap: false

google_analytics: G-NWTG8BT7S6
permalink: /:categories/:year/:month/:title:output_ext