title: Christian Helle's Blog
# email: someone@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog is dedicated to the art of building software.
  I write about my creations, discoveries, and solutions to problems
  that I encounter while building software.
baseurl: "/"
url: "https://christianhelle.github.io"
twitter_username: christianhelle
github_username:  christianhelle

markdown: kramdown
highlighter: rouge

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
show_excerpts: true

gist:
  noscript: false
future: true 
jailed: false