title: Christian Helle's Blog
email: christian.helle@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog is dedicated to the art of building software.
  I write about my creations, discoveries, and solutions to problems
  that I encounter while building software.
baseurl: "/"
url: "https://christianhelle.github.io"
twitter_username: christianhelle
github_username:  christianhelle

markdown: kramdown
highlighter: rouge

theme: minima
plugins:
  - jekyll-paginate

minima:
  skin: dark

paginate: 5
paginate_path: /page/:num/
google_analytics: UA-141206907-2
permalink: /:categories/:year/:month/:title:output_ext