name: Test for broken links

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/broken-link-detector.yml"
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test site for broken links
    steps:
      - name: Install Argiope
        shell: pwsh
        run: |
          curl -fsSL https://christianhelle.com/argiope/install | sh
      - name: Run Argiope Check
        run: argiope check https://christianhelle.com --report broken-links-report.txt
      - name: Publish results
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            broken-links-report.txt

