name: Test for broken links

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/production-crawler.yml"
    branches:
      - "*"
  schedule:
    - cron: "0 * * * *"

jobs:
  windows:
    runs-on: windows-latest
    name: Test site for broken links
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install LinkChecker
        run: pip install linkchecker
      - name: Run LinkChecker
        run: |
          linkchecker https://christianhelle.com --check-extern > broken-links-report.txt
          cat broken-links-report.txt
      - name: Publish results
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            broken-links-report.txt
